server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: integration_app
    url: jdbc:postgresql://localhost:5432/fraud
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    exchanges:
      internal: internal.exchange
    queues:
      notification: fraud.queue
    routing-keys:
      internal-notification: internal.fraud.routing-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

